export const ActionTypes = {
  LOAD_USER: "LOAD_USER",
  SIGNUP_USER: "SIGNUP_USER",
  LOGIN_USER: "LOGIN_USER",
  LOGOUT_USER: "LOGOUT_USER",
  SET_TEST_PAGE_DATA: "SET_TEST_PAGE_DATA",
  SET_FEATURED_DATA: "SET_FEATURED_DATA",
  GET_SINGLE_APARTMENT: "GET_SINGLE_APARTMENT",
  GET_ALL_APARTMENTS: "GET_ALL_APARTMENTS",
  SET_RANDOM_APARTMENT_IMAGE: "SET_RANDOM_APARTMENT_IMAGE",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
  SET_BAD_REQUEST: "SET_BAD_REQUEST",
  IS_FETCHING_DATA: "IS_FETCHING_DATA",
  SET_USER_INFO: "SET_USER_INFO",
  NO_INTERNET: "NO_INTERNET",
  SET_HIGHEST_PRICE_SIZE_AND_CAPACITY_DATA:
    "SET_HIGHEST_PRICE_SIZE_AND_CAPACITY_DATA",
  // SET_SEARCH_RESULT: "SET_SEARCH_RESULT",
};
