export const ActionTypes = {
  SET_TEST_PAGE_DATA: "SET_TEST_PAGE_DATA",
  GET_SINGLE_ROOM: "GET_SINGLE_ROOM",
  IS_FETCHING_DATA: "IS_FETCHING_DATA",
  NO_INTERNET: "NO_INTERNET",
  SET_SEARCH_RESULT: "SET_SEARCH_RESULT",
};
