export const ActionTypes = {
  SET_TEST_PAGE_DATA: "SET_TEST_PAGE_DATA",
  SET_FEATURED_DATA: "SET_FEATURED_DATA",
  GET_SINGLE_APARTMENT: "GET_SINGLE_APARTMENT",
  GET_ALL_APARTMENTS: "GET_ALL_APARTMENTS",
  SET_BAD_REQUEST: "SET_BAD_REQUEST",
  IS_FETCHING_DATA: "IS_FETCHING_DATA",
  NO_INTERNET: "NO_INTERNET",
  SET_HIGHEST_PRICE_AND_CAPACITY_DATA: "SET_HIGHEST_PRICE_AND_CAPACITY_DATA",
  // SET_SEARCH_RESULT: "SET_SEARCH_RESULT",
};
